version: "3.9"  # optional since v1.27.0
services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_DB_CONNECTION_STRING=mongodb://peter:mongo@mongo:27017
      - MONGO_DB_NAME=gcp
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis
      - mongo
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=peter
      - MONGO_INITDB_ROOT_PASSWORD=mongo

volumes:
  mongo-data:
  redis-data: